# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
